requestsUtil.py-27-2022-03-06 14:44:10,880-INFO-开始post请求
AssertUtil.py-13-2022-03-06 14:44:11,087-ERROR-公共断言失败,接口返回码错误
requestsUtil.py-27-2022-03-06 14:44:41,127-INFO-开始post请求
AssertUtil.py-13-2022-03-06 18:14:47,410-ERROR-公共断言失败,接口返回码错误
AssertUtil.py-13-2022-03-06 18:16:05,998-ERROR-公共断言失败,接口返回码错误
AssertUtil.py-13-2022-03-06 18:17:18,773-ERROR-公共断言失败,接口返回码错误
AssertUtil.py-13-2022-03-06 18:17:53,154-ERROR-公共断言失败,接口返回码错误
AssertUtil.py-13-2022-03-06 18:19:05,129-ERROR-公共断言失败,接口返回码错误
AssertUtil.py-13-2022-03-06 18:20:53,688-ERROR-公共断言失败,接口返回码错误
AssertUtil.py-13-2022-03-06 18:23:42,889-ERROR-公共断言失败,接口返回码错误
AssertUtil.py-13-2022-03-06 18:23:58,464-ERROR-公共断言失败,接口返回码错误
AssertUtil.py-13-2022-03-06 18:25:00,217-ERROR-公共断言失败,接口返回码错误
AssertUtil.py-13-2022-03-06 18:25:39,358-ERROR-公共断言失败,接口返回码错误
AssertUtil.py-14-2022-03-06 18:25:39,359-INFO-{"header":{"version":2,"flag":0},"body":{"cmd":"GetBannerList","payload":{"total":53,"banner_list":[{"status":0,"redirect":"","sort":0,"entry_type":1,"title":"1111111go","banner_id":"2c1981b5-4c5a-47e8-b99a-7b2ea01b9cac","image_url":"https://tsep-test-1304685099.cos.ap-guangzhou.myqcloud.com/tsep_dev/60801202/c8be6876-c96b-43e0-8fb0-b25eb9bd18d7","release_time":0,"preview_url":""},{"status":1,"redirect":"0a9a277c-676f-4be7-a281-cb45b2592711","sort":0,"entry_type":1,"title":"前端Gocc测试","banner_id":"b73671f5-308d-4b00-bcaf-ea470e3faae6","image_url":"https://tsep-test-1304685099.cos.ap-guangzhou.myqcloud.com/tsep_dev/41701202/42d1ef1c-d141-4dd4-bace-3771c53ea5c1","release_time":1626224031,"preview_url":""},{"status":1,"redirect":"f0b59f23-b6d3-4a5e-b948-275e08ad83f0","sort":0,"entry_type":1,"title":"yt_test","banner_id":"d80ccc22-dc8b-424e-a54d-1759549503c2","image_url":"https://tsep-test-1304685099.cos.ap-guangzhou.myqcloud.com/tsep_dev/02701202/75eac9d5-1ca8-4e67-a95b-29f876f68cd5","release_time":0,"preview_url":""},{"status":1,"redirect":"0217b554-c540-4c8d-9e86-daac4baca123","sort":0,"entry_type":1,"title":"111","banner_id":"dbc0768a-f52c-4fb3-965b-4ccbb378dfb4","image_url":"https://tsep-test-1304685099.cos.ap-guangzhou.myqcloud.com/tsep_dev/41701202/1235210c-5ab5-4a34-b191-0f6a3c559d8f","release_time":1626215242,"preview_url":""},{"status":0,"redirect":"","sort":0,"entry_type":1,"title":"测试","banner_id":"01656fa0-ab1b-4b2d-8115-29205c7720f2","image_url":"https://tsep-test-1304685099.cos.ap-guangzhou.myqcloud.com/tsep_dev/01102202/3b75589c-c924-4993-b012-22a0e0b5d6d2","release_time":0,"preview_url":""},{"status":1,"redirect":"","sort":0,"entry_type":1,"title":"测试","banner_id":"3344d040-148d-43a3-8e6f-70179b30159d","image_url":"https://tsep-test-1304685099.cos.ap-guangzhou.myqcloud.com/tsep_dev/60701202/ce593268-0e82-4186-ba9c-327f521b25cb","release_time":0,"preview_url":""},{"status":0,"redirect":"","sort":0,"entry_type":1,"title":"10","banner_id":"3b18840c-4ddd-456e-9cfd-90bf6348d1ed","image_url":"https://tsep-test-1304685099.cos.ap-guangzhou.myqcloud.com/tsep_dev/62501202/ad7177f2-64f6-4b8e-8f0f-bdc0e9ba3e05","release_time":0,"preview_url":""},{"status":1,"redirect":"11","sort":0,"entry_type":1,"title":"测试","banner_id":"498023bf-f59f-44b7-8ac1-3cf8b7ba9c1e","image_url":"https://tsep-test-1304685099.cos.ap-guangzhou.myqcloud.com/tsep_dev/72701202/db74275e-f38c-46cc-8112-ab0d61aa1ea7","release_time":0,"preview_url":""},{"status":0,"redirect":"","sort":0,"entry_type":1,"title":"6","banner_id":"4d90c5bf-8b65-4d02-8b3c-3fd7d4667bc8","image_url":"https://tsep-test-1304685099.cos.ap-guangzhou.myqcloud.com/tsep_dev/62501202/bdaed7b7-48d0-4cd4-b0cb-f5a471616e58","release_time":0,"preview_url":""},{"status":0,"redirect":"","sort":0,"entry_type":1,"title":"16","banner_id":"63d6408b-a4da-4c82-bfee-e15e1e561176","image_url":"https://tsep-test-1304685099.cos.ap-guangzhou.myqcloud.com/tsep_dev/62501202/74152767-c867-4fc7-8c6f-5d2e4b2f3489","release_time":0,"preview_url":""}],"err_code":0,"err_msg":""},"seq":0,"traceid":"f344acf5-f4c7-46e7-a343-28503f98da22","message":"success","retcode":0,"bizcode":0}}
AssertUtil.py-13-2022-03-06 18:27:17,986-ERROR-公共断言失败,接口返回码错误
AssertUtil.py-13-2022-03-06 18:27:59,733-ERROR-公共断言失败,接口返回码错误
AssertUtil.py-14-2022-03-06 18:27:59,734-INFO-<class 'str'>
AssertUtil.py-13-2022-03-06 18:29:08,509-ERROR-公共断言失败,接口返回码错误
AssertUtil.py-14-2022-03-06 18:29:08,510-INFO-<class 'str'>
AssertUtil.py-13-2022-03-06 18:32:11,030-ERROR-公共断言失败,接口返回码错误
